package models

const (
	TASK_DNS        = 1
	TASK_ICMP       = 2
	TASK_HTTP       = 3
	TASK_TRACEROUTE = 4
	//
	PROTO_TCP = 1
	PROTO_UDP = 2
	//
	STATUS_INITIATED_BY_SCHEDULER           = 1
	STATUS_PUBLISHED_TO_REDIS_BY_SCHEDULER  = 2
	STATUS_RECEIVED_BY_SERVER               = 3
	STATUS_SENT_TO_SENSOR_BY_SERVER         = 4
	STATUS_RECEIVED_BY_SENSOR               = 5
	STATUS_RESULTS_SENT_TO_SERVER_BY_SENSOR = 6
	STATUS_RESULTS_RECEIVED_BY_SERVER       = 7
	STATUS_DONE                             = 8
	STATUS_ERROR                            = 9
	//
	USER_GROUP_ROOT  = 1
	USER_GROUP_ADMIN = 2
	USER_GROUP_USER  = 3
	//
	PERMISSION_READ            = 1
	PERMISSION_CREATE          = 2
	PERMISSION_UPDATE          = 3
	PERMISSION_DELETE          = 4
	PERMISSION_CREATE_ORG_USER = 5
)
