version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: postgres
    networks:
      - default
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_config:/etc/postgres
      - postgres_data:/var/lib/postgres

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=16
networks:
  default:

volumes:
  postgres_config:
  postgres_data: