# PING42 Development Compose file

services:
  timescale:
    image: timescale/timescaledb-ha:pg16
    container_name: timescale
    hostname: timescale
    networks:
      - default
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_config:/etc/postgres
      - postgres_data:/var/lib/postgres

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=16

networks:
  default:

volumes:
  postgres_config:
  postgres_data:
